name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: vouch-opensource/tools.deps-build@1.0.1
        with:
          alias: :test
